<?php
namespace grozzzny\sitemap;

use Yii;
use yii\base\InvalidArgumentException;
use yii\easyii2\components\FastModule;

class Module extends FastModule
{
    public $domain;

    public $generatedByName = 'PRkenig';
    public $generatedByLink = 'http://pr-kenig.ru';

    public $settings = [
        'modelSitemap' => '\grozzzny\sitemap\models\Sitemap',
    ];

    public function init()
    {
        if(empty($this->domain) && is_a(Yii::$app,'yii\console\Application')) throw new InvalidArgumentException('Invalid param domain');
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function getTitle()
    {
        // TODO: Implement getTitle() method.
        return Yii::t('app', 'Sitemap');
    }

    public function getName()
    {
        // TODO: Implement getName() method.
        return $this->id;
    }

    public function getIcon()
    {
        // TODO: Implement getIcon() method.
        return 'globe';
    }
}