<?php
namespace grozzzny\sitemap;

use Yii;
use yii\base\InvalidArgumentException;

class SitemapModule extends \yii\base\Module
{
    public $domain;

    public $generatedByName = 'PRkenig';
    public $generatedByLink = 'https://pr-kenig.ru';

    public function init()
    {
        if(empty($this->domain) && is_a(Yii::$app,'yii\console\Application')) throw new InvalidArgumentException('Invalid param domain');
        parent::init(); // TODO: Change the autogenerated stub
    }
}